"""initial schema

Revision ID: 272504d65f4b
Revises: 
Create Date: 2026-10-04 02:34:25.279231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272504d65f4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'name', name='uq_section_station_name')
    )
    op.create_table('prepared_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_de', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preparation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prepared_product_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('TO_PREPARE', 'COMPLETED', name='ck_task_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['prepared_product_id'], ['prepared_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_task_per_product_due_date', 'preparation_tasks', ['prepared_product_id', 'due_date'], unique=True, sqlite_where=sa.text("status = 'TO_PREPARE'"), postgresql_where=sa.text("status = 'TO_PREPARE'"))
    op.create_table('product_location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prepared_product_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prepared_product_id'], ['prepared_products.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_location_history')
    op.drop_index('uq_active_task_per_product_due_date', table_name='preparation_tasks', sqlite_where=sa.text("status = 'TO_PREPARE'"), postgresql_where=sa.text("status = 'TO_PREPARE'"))
    op.drop_table('preparation_tasks')
    op.drop_table('prepared_products')
    op.drop_table('sections')
    op.drop_table('workers')
    op.drop_table('storage_locations')
    op.drop_table('stations')
    # ### end Alembic commands ###
